# Generated by Django 3.1.1 on 2021-02-27 18:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('number_of_books', models.IntegerField(default=0, verbose_name='Number of Books Published')),
            ],
            options={
                'ordering': ['number_of_books', 'first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('international_standard_book_number', models.CharField(max_length=13, unique=True)),
                ('synopsis', models.TextField(max_length=1000)),
                ('author', models.ManyToManyField(to='system.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Book Genre (e.g. Narrative Non-Fiction)', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, choices=[('l', 'Lent'), ('a', 'Available'), ('b', 'Booked'), ('r', 'Reserved')], default='m', help_text='Book availability', max_length=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='system.book')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='system.Genre'),
        ),
    ]
