# Generated by Django 3.1.1 on 2021-02-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20210227_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['status'], 'verbose_name_plural': 'Inventories'},
        ),
    ]
