# Generated by Django 3.1.1 on 2021-02-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_inventory_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='borrow_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
