# Generated by Django 3.1.1 on 2021-02-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20210227_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='genre',
        ),
    ]
