# Generated by Django 3.1.1 on 2021-02-28 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20210228_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='international_standard_book_number',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='Select author for this book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Select genre for this book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.genre'),
        ),
    ]
